/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ŞerafettinDoruk_SEZER_2021221038_bp2_Project;

import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Lenovo
 */
public class Main_bridge extends javax.swing.JFrame {

    Connection con = null;
    PreparedStatement pst = null;
    ResultSet rs = null;

    /**
     * Creates new form Main_bridge
     */
    public Main_bridge() {
        initComponents();
        // NewAccountsConnection klasındaki NewAccountsConnectionDB fonksiyonunu çalıştırıyor.
        con = NewAccountsConnection.NewAccountsConnectionDB();
        // Uygulamayı sayfanın ortasında başlatıyor.
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jSplitPane1 = new javax.swing.JSplitPane();
        jPanel1 = new javax.swing.JPanel();
        btn_Accounts = new javax.swing.JButton();
        btn_patient_chart = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        btn_patient_login = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel1.setText("MAIN BRIDGE");

        jSplitPane1.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);
        jSplitPane1.setMinimumSize(new java.awt.Dimension(600, 600));
        jSplitPane1.setPreferredSize(new java.awt.Dimension(600, 600));

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "TABLES", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 18))); // NOI18N
        jPanel1.setMinimumSize(new java.awt.Dimension(300, 300));
        jPanel1.setPreferredSize(new java.awt.Dimension(300, 300));

        btn_Accounts.setText("Accounts");
        btn_Accounts.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_AccountsActionPerformed(evt);
            }
        });

        btn_patient_chart.setText("Patient Chart");
        btn_patient_chart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_patient_chartActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_patient_chart, javax.swing.GroupLayout.PREFERRED_SIZE, 439, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_Accounts, javax.swing.GroupLayout.PREFERRED_SIZE, 439, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 88, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(btn_Accounts, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(btn_patient_chart, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(83, Short.MAX_VALUE))
        );

        jSplitPane1.setTopComponent(jPanel1);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Patient Procedures", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 18))); // NOI18N
        jPanel2.setMinimumSize(new java.awt.Dimension(300, 300));
        jPanel2.setPreferredSize(new java.awt.Dimension(300, 300));

        btn_patient_login.setText("Patient Login");
        btn_patient_login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_patient_loginActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(btn_patient_login, javax.swing.GroupLayout.PREFERRED_SIZE, 446, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(83, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(btn_patient_login, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jSplitPane1.setRightComponent(jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(jSplitPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 559, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(206, 206, 206)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(39, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(jSplitPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 445, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(35, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_patient_loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_patient_loginActionPerformed
        // Who clasındaki Who2 stringi karşılaştırma için buraya getirdim.

        // kişinin girmiş olduğu who değerini baz aldım.
        try {
            String sql = "SELECT * From NewAccounts WHERE Who ='" + Who.Who2 + "'";
            Statement st = con.createStatement();
            rs = st.executeQuery(sql);

            if (rs.next()) {
                // Who2 değerini W atıp,Administrator, Doctor ve User olup olmadığını buldum ve mesaj bölümüne yazıp. kişiyi Patient_LOgin jFrame yolladım
                String W = Who.Who2;
                if (W.contains("Administrator") || W.contains("Doctor") || W.contains("User")) {
                    JOptionPane.showMessageDialog(this, "You are " + Who.Who2);
                     java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Patient_Login().setVisible(true);
            }
        });
                    this.dispose();
                } else {
                    JOptionPane.showMessageDialog(this, "You aren't " + Who.Who2);
                }

            }

        } catch (HeadlessException | SQLException e) {
            JOptionPane.showMessageDialog(this, "Programe is failed" + e);
        }


    }//GEN-LAST:event_btn_patient_loginActionPerformed

    private void btn_patient_chartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_patient_chartActionPerformed
         // Who clasındaki Who2 stringi karşılaştırma için buraya getirdim.

        // kişinin girmiş olduğu who değerini baz aldım.
        try {
            String sql = "SELECT * From NewAccounts WHERE Who ='" + Who.Who2 + "'";
            Statement st = con.createStatement();
            rs = st.executeQuery(sql);

            if (rs.next()) {
                // Who2 değerini W atıp, Kişinin Who değeri Administrator veya Doctor ise Patient_chart'ta girmesini sağladım.
                // Administrator veya Doctor değilse You aren't Administrator or Doctor, uyarı mesajını yazmasını sağladım.
                String W = Who.Who2;
                if (W.contains("Administrator") || W.contains("Doctor")) {
                    JOptionPane.showMessageDialog(this, "You are " + Who.Who2);
                    java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Patient_Chart().setVisible(true);
            }
        });
                    this.dispose();
                } else {
                    JOptionPane.showMessageDialog(this, "You aren't Administrator or Doctor", "Warning", JOptionPane.WARNING_MESSAGE);

                }

            }

        } catch (HeadlessException | SQLException e) {
            JOptionPane.showMessageDialog(this, "Programe is failed" + e);
        }
    }//GEN-LAST:event_btn_patient_chartActionPerformed

    private void btn_AccountsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_AccountsActionPerformed
         // Who clasındaki Who2 stringi karşılaştırma için buraya getirdim.

        // kişinin girmiş olduğu who değerini baz aldım.
        try {
            String sql = "SELECT * From NewAccounts WHERE Who ='" + Who.Who2 + "'";
            Statement st = con.createStatement();
            rs = st.executeQuery(sql);

            if (rs.next()) {
                // Who2 değerini W atıp, Kişinin Who değeri sadece Administrator ise Accounts2'ya girmesini sağladım.
                // Administrator değilse You aren't Administrator, uyarı mesajını yazmasını sağladım.
                String W = Who.Who2;
                if (W.contains("Administrator")) {
                    JOptionPane.showMessageDialog(this, "You are " + Who.Who2);
                    Accounts2 AC = new Accounts2();
                    AC.setVisible(true);
                    AC.pack();
                    AC.setLocationRelativeTo(null);
                    AC.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
                    this.dispose();
                } else {
                    JOptionPane.showMessageDialog(this, "You aren't Administrator", "Warning", JOptionPane.WARNING_MESSAGE);
                }

            }

        } catch (HeadlessException | SQLException e) {
            JOptionPane.showMessageDialog(this, "Programe is failed" + e);
        }

    }//GEN-LAST:event_btn_AccountsActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main_bridge.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main_bridge.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main_bridge.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main_bridge.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main_bridge().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Accounts;
    private javax.swing.JButton btn_patient_chart;
    private javax.swing.JButton btn_patient_login;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSplitPane jSplitPane1;
    // End of variables declaration//GEN-END:variables
}
